service: insta-clone-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-2

  environment:
    USER_TABLE: "users-${opt:stage, self:provider.stage}"
    POST_TABLE: "posts-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  signInUser:
    handler: api/auth.signin
    memorySize: 128
    description: Signin user
    events:
      - http: 
          path: api/auth/signin
          method: post
  signUpUser:
    handler: api/auth.signup
    memorySize: 128
    description: User Account creation
    events:
      - http: 
          path: api/auth/signup
          method: post 

  # candidateDetails:
  #   handler: api/candidate.get
  #   events:
  #     - http:
  #         path: candidates/{id}
  #         method: get

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "username"
            AttributeType: "S"
          - AttributeName: "password"
            AttributeType: "S"
          - AttributeName: "fullName"
            AttributeType: "S"
          - AttributeName: "bithday"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          # - AttributeName: "username"
          #   KeyType: "HASH"
          # - AttributeName: "password"
          #   KeyType: "RANGE"
          # - AttributeName: "fullName"
          #   KeyType: "RANGE"
          # - AttributeName: "bithday"
          #   KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"